<!DOCTYPE html>
<!-- If you’re looking for the online demo, it’s here: http://mathiasbynens.be/demo/placeholder -->
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Narwi</title>
		<style>
			body, input, textarea { font: 1em/1.4 Helvetica, Arial; }
			label code { cursor: pointer; float: left; width: 150px; }
			
			
			/* #p { background: lime; } */
		</style>
	</head>
	<body style="margin:0px;">
		<table border="0" cellpadding="0" cellspacing="0" width="100%" style="margin:0 auto;text-align:center;">
			<!-- header -->
			 <tr>
				  <td style="background-color:#4d4d4d;padding:10px 10%;" >
				  	<div style="overflow:hidden;">
				  		<a href="http://www.narwi.org" style="float:left;"><img src="<?= $this->client_url?>img/client_logo.png" ></a>
				  		<!-- <a style="float:right;color:#ffffff;font-size:16px;padding:14px;text-decoration:none;" href="">View in Browser</a> -->
				  	</div>
				  </td>
			 </tr>
			 <!-- header ending -->
			 <tr>
			      <td style="background: #07acf6 url(<?= $this->client_url.'img/repayment.jpg'?>) no-repeat 100%;  height: 200px;  padding: 94px 0px;">
			       <!-- <img style="width:100%;" src="http://localhost/narwi/narwi-web-client/public/img/updateemail.jpg"> -->
			       <div style="width:300px;width:300px;text-align:left;float:right;margin-right:10%;color:#ffffff;font-size:42px;">Final Repayment Update Email</div>
			      </td>
			 </tr>
			 <tr>
				  <td style="padding:10px 10%;">
				  	<h2 style="margin:0px;font-size:30px;color:#ff5340;">HI <span style="text-transform:uppercase;color:#ff5340;"><?= $this->user['fullName'];?></span></h2>
				  </td>
			 </tr>
			 <tr>
				  <td style="padding:10px 10%;">
				  	<p style="margin:0px auto;font-size:20px;max-width:700px;"><?= $this->transaction['loan']['name'];?> has made the final repayment to your Narwi-Waqf in the amount of $<?= $this->amount_received;?>!  You currently have a balance of $<?= $this->user['wallet_amount'];?> in your Narwi-Waqf. You can find more detailed information in the <a href="<?= $this->client_url ?>" style="text-decoration:none;color:#07acf6;">Narwi-Waqf Dashboard</a>.</p>
				  </td>
			 </tr>
			 <tr>
				  <td style="padding:10px 10%;">
				  	<p style="margin:0px auto;font-size:20px;max-width:700px;">You can now disperse your Narwi-Waqf support another micro-entrepreneur, or make a donation to help cover Narwi’s operational costs. </p>
				  </td>
			 </tr>
			 <tr>
				  <td style="padding:10px 10%;">
				  	<p style="margin:0px auto;font-size:20px;max-width:700px;">We hope you enjoyed your experience on Narwi and issue another Narwi-Waqf very soon.  </p>
				  </td>
			 </tr>
			 <tr>
				  <td style="padding:10px 10%;">
				  	<p style="margin:0px auto;font-size:20px;max-width:700px;">If you have any questions, you can reach us anytime at <a href="mailto:info@narwi.org" style="color:#ffffff;font-weight:bold;">info@narwi.org.</a> </p>
				  </td>
			 </tr>
			 <tr>
				  <td style="padding:10px 10%;">
				  	<p style="color:#ff5340;margin:0px auto;font-size:20px;max-width:700px;">Blessed Giving! </p>
				  </td>
			 </tr>
			 <tr>
				  <td style="padding:10px 10%;">
				  	<p style="margin:0px auto;font-size:20px;max-width:700px;">The Narwi Team </p>
				  </td>
			 </tr>
			 <tr>
				  <td style="padding:4px 10%;">
				  	<p style="margin:0px auto;font-size:20px;max-width:700px;">We tell their stories. You help write them. </p>
				  </td>
			 </tr>
			 <tr>
				  <td style="padding:10px 10%;">
				  	<p style="margin:0px auto;font-size:20px;max-width:700px;">Please help us spread the word </p>
				  </td>
			 </tr>
			  <tr>
				  <td style="padding:10px 10% 20px;;">
				  	<a href="" style="display:inline-block;padding:10px 20px;border:1px solid #000000;font-size:20px;text-decoration:none;color:#000000;">SHARE THE GOOD NEWS</a>
				  </td>
			 </tr>
			 <!-- footer -->
			 <tr>
				  <td style="background-color:#4d4d4d;padding:10px 10%;" >
				  	<div style="display:inline-block;vertical-align:middle;">
				  		<a  href=""><img style="width:30px;margin-right:10px;" src="<?= $this->client_url?>img/facebook_share.png"></a>
				  		<a  href=""><img style="width:30px;margin-right:10px;" src="<?= $this->client_url?>img/twitter_share.png"></a>
				  		<a  href=""><img style="width:30px;margin-right:10px;" src="<?= $this->client_url?>img/linkedin_share.png"></a>
				  	</div>
				  	<p style="display:inline-block;vertical-align:middle;color:#ffffff;">© 2015 Narwi.org. 
				 <!--  	<span style="color:#07acf6;"><a style="color:#07acf6;text-decoration:none;" href="">Unsubscribe</a> | <a style="color:#07acf6;text-decoration:none;" href="">Update email reference</a></span> -->
				  	</p>
				  </td>
			 </tr>
		</table>
	</body>
</html>
