 <!DOCTYPE html>
<!-- If you’re looking for the online demo, it’s here: http://mathiasbynens.be/demo/placeholder -->
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Narwi</title>
		<style>
			body, input, textarea { font: 1em/1.4 Helvetica, Arial; }
			label code { cursor: pointer; float: left; width: 150px; }
			
			
			/* #p { background: lime; } */
		</style>
	</head>
	<body style="margin:0px;">
		<table border="0" cellpadding="0" cellspacing="0" width="100%" style="margin:0 auto;text-align:center;">
			<!-- header -->
			 <tr>
				  <td style="background-color:#4d4d4d;padding:10px 10%;" >
				  	<div style="overflow:hidden;">
				  		<a href="http://www.narwi.org" style="float:left;"><img src="http://54.69.27.231/narwi/narwi-web-client/public/img/client_logo.png" ></a>
				  		<!-- <a style="float:right;color:#ffffff;font-size:16px;padding:14px;text-decoration:none;" href="">View in Browser</a> -->
				  	</div>
				  </td>
			 </tr>
			 <!-- header ending -->
			 <tr>
				  <td style="padding:10px 10%;">
				  	<h1>Narwi Loan</h1>
			  		<p style="font-size:30px;margin:0px;">Name: <?= $this->name;?></p>
			  		<p style="font-size:20px;margin:0px;">Message:<?= $this->message;?></p>
			  		<p style="font-size:20px;margin:0px;">Loan Details:<?= $this->loan['name']; ?></p>
				  </td>
			 </tr>
			 <!-- footer -->
			 <tr>
				  <td style="background-color:#4d4d4d;padding:10px 10%;" >
				  	<div style="display:inline-block;vertical-align:middle;">
				  		<a  href=""><img style="width:30px;margin-right:10px;" src="http://54.69.27.231/narwi/narwi-web-client/public/img/facebook_share.png"></a>
				  		<a  href=""><img style="width:30px;margin-right:10px;" src="http://54.69.27.231/narwi/narwi-web-client/public/img/twitter_share.png"></a>
				  		<a  href=""><img style="width:30px;margin-right:10px;" src="http://54.69.27.231/narwi/narwi-web-client/public/img/linkedin_share.png"></a>
				  	</div>
				  	<p style="display:inline-block;vertical-align:middle;color:#ffffff;">© 2015 Narwi.org. 
				  	</p>
				  </td>
			 </tr>
		</table>
	</body>
</html>

